In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Load Excel File
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

In [3]:
## Filtering 
car_filter = df['car_type']=='Toyota Sienna'
interest_filter = df['interest_rate']==0.0702
df = df.loc[car_filter & interest_filter, :]

In [4]:
# Approach 1 dictionary substitution using rename method
df = df.rename(columns={'Starting Balance': 'starting_balance',
                        'Interest Paid': 'interest_paid', 
                        'Principal Paid': 'principal_paid',
                        'New Balance': 'new_balance'})

In [5]:
# Approach 2 list replacement
# Only changing Month -> month, but we need to list the rest of the columns
df.columns = ['month',
              'starting_balance',
              'Repayment',
              'interest_paid',
              'principal_paid',
              'new_balance',
              'term',
              'interest_rate',
              'car_type']

In [6]:
# Approach 1
# This approach allows you to drop multiple columns at a time 
df = df.drop(columns=['term'])

In [7]:
# Approach 2 use the del command
del df['Repayment']

In [8]:
df.shape

(60, 7)

In [9]:
df.head()

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,1,34689.96,202.93,484.30,34205.66,0.0702,Toyota Sienna
1,2,34205.66,200.10,487.13,33718.53,0.0702,Toyota Sienna
2,3,33718.53,197.25,489.98,33228.55,0.0702,Toyota Sienna
3,4,33228.55,194.38,492.85,32735.70,0.0702,Toyota Sienna
4,5,32735.70,191.50,495.73,32239.97,0.0702,Toyota Sienna

## Aggregate Methods
It is often a good idea to compute summary statistics.

Aggregate Method | Description
--- | --- 
sum | sum of values
cumsum | cumulative sum
mean | mean of values
median | arithmetic median of values
min | minimum
max | maximum
mode | mode
std | unbiased standard deviation
var | unbiased variance
quantile | compute rank-based statistics of elements

In [10]:
df.head()

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,1,34689.96,202.93,484.30,34205.66,0.0702,Toyota Sienna
1,2,34205.66,200.10,487.13,33718.53,0.0702,Toyota Sienna
2,3,33718.53,197.25,489.98,33228.55,0.0702,Toyota Sienna
3,4,33228.55,194.38,492.85,32735.70,0.0702,Toyota Sienna
4,5,32735.70,191.50,495.73,32239.97,0.0702,Toyota Sienna

In [11]:
# sum the values in a column
# total amount of interest paid over the course of the loan
df['interest_paid'].sum()

5022.959999999999

In [12]:
# sum all the values across all columns
df.sum()

month                                                            1830
starting_balance                                           1118598.13
interest_paid                                                 5022.96
principal_paid                                               34690.29
new_balance                                                1083907.84
interest_rate                                                   4.212
car_type            Toyota SiennaToyota SiennaToyota SiennaToyota ...
dtype: object

In [13]:
'Toyota Sienna' + 'Toyota Sienna'

'Toyota SiennaToyota Sienna'

In [14]:
# Notice that by default it seems like the sum function ignores missing values. 
help(df['interest_paid'].sum)

Help on method sum in module pandas.core.series:

sum(axis: 'Axis | None' = None, skipna: 'bool' = True, numeric_only: 'bool' = False, min_count: 'int' = 0, **kwargs) method of pandas.core.series.Series instance
    Return the sum of the values over the requested axis.

    This is equivalent to the method ``numpy.sum``.

    Parameters
    ----------
    axis : {index (0)}
        Axis for the function to be applied on.
        For `Series` this parameter is unused and defaults to 0.

        .. warning::

            The behavior of DataFrame.sum with ``axis=None`` is deprecated,
            in a future version this will reduce over both axes and return a scalar
            To retain the old behavior, pass axis=0 (or do not pass axis).

        .. versionadded:: 2.0.0

    skipna : bool, default True
        Exclude NA/null values when computing the result.
    numeric_only : bool, default False
        Include only float, int, boolean columns. Not implemented for Series.

    min_count : int, default 0
        The required number of valid values to perform the operation. If fewer than
        ``min_count`` non-NA values are present the result will be NA.
    **kwargs
        Additional keyword arguments to be passed to the function.

    Returns
    -------
    scalar or scalar

    See Also
    --------
    Series.sum : Return the sum.
    Series.min : Return the minimum.
    Series.max : Return the maximum.
    Series.idxmin : Return the index of the minimum.
    Series.idxmax : Return the index of the maximum.
    DataFrame.sum : Return the sum over the requested axis.
    DataFrame.min : Return the minimum over the requested axis.
    DataFrame.max : Return the maximum over the requested axis.
    DataFrame.idxmin : Return the index of the minimum over the requested axis.
    DataFrame.idxmax : Return the index of the maximum over the requested axis.

    Examples
    --------
    >>> idx = pd.MultiIndex.from_arrays([
    ...     ['warm', 'warm', 'cold', 'cold'],
    ...     ['dog', 'falcon', 'fish', 'spider']],
    ...     names=['blooded', 'animal'])
    >>> s = pd.Series([4, 2, 0, 8], name='legs', index=idx)
    >>> s
    blooded  animal
    warm     dog       4
             falcon    2
    cold     fish      0
             spider    8
    Name: legs, dtype: int64

    >>> s.sum()
    14

    By default, the sum of an empty or all-NA Series is ``0``.

    >>> pd.Series([], dtype="float64").sum()  # min_count=0 is the default
    0.0

    This can be controlled with the ``min_count`` parameter. For example, if
    you'd like the sum of an empty series to be NaN, pass ``min_count=1``.

    >>> pd.Series([], dtype="float64").sum(min_count=1)
    nan

    Thanks to the ``skipna`` parameter, ``min_count`` handles all-NA and
    empty series identically.

    >>> pd.Series([np.nan]).sum()
    0.0

    >>> pd.Series([np.nan]).sum(min_count=1)
    nan

In [15]:
# The info method gives the column datatypes + number of non-null values
# Notice that we seem to have 60 non-null values for all but the Interest Paid column. 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             60 non-null     int64
 1   starting_balance  60 non-null     float64
 2   interest_paid     50 non-null     float64
 3   principal_paid    60 non-null     float64
 4   new_balance       60 non-null     float64
 5   interest_rate     60 non-null     float64
 6   car_type          60 non-null     object
dtypes: float64(5), int64(1), object(1)
memory usage: 3.8+ KB