In [1]:
# Import libraries
import pandas as pd
import numpy as np

In [2]:
# Load Excel File
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

In [3]:
## Filtering 
car_filter = df['car_type']=='Toyota Sienna'
interest_filter = df['interest_rate']==0.0702
df = df.loc[car_filter & interest_filter, :]

In [4]:
# Approach 1 dictionary substitution using rename method
df = df.rename(columns={'Starting Balance': 'starting_balance',
                        'Interest Paid': 'interest_paid', 
                        'Principal Paid': 'principal_paid',
                        'New Balance': 'new_balance'})

In [5]:
# Approach 2 list replacement
# Only changing Month -> month, but we need to list the rest of the columns
df.columns = ['month',
              'starting_balance',
              'Repayment',
              'interest_paid',
              'principal_paid',
              'new_balance',
              'term',
              'interest_rate',
              'car_type']

In [6]:
# Approach 1
# This approach allows you to drop multiple columns at a time 
df = df.drop(columns=['term'])

In [7]:
# Approach 2 use the del command
del df['Repayment']

In [8]:
df.shape

(60, 7)

## Identifying Missing Data
Values will be originally missing from a dataset or be a product of data manipulation. In pandas, missing values are typically called `NaN` or `None`.

Missing data can: 
* Hint at data collection errors.
* Indicate improper conversion or manipulation.
* Actually not be considered missing. For some datasets, missing data can be listed as "zero", "false", "not applicable", "entered an empty string", among other possibilities. 

This is an important subject as before you can graph data, you should make sure you aren't trying to graph some missing values as that can cause an error or misinterpretation of the data.

### Finding Missing Values

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             60 non-null     int64
 1   starting_balance  60 non-null     float64
 2   interest_paid     59 non-null     float64
 3   principal_paid    60 non-null     float64
 4   new_balance       60 non-null     float64
 5   interest_rate     60 non-null     float64
 6   car_type          60 non-null     object
dtypes: float64(5), int64(1), object(1)
memory usage: 3.8+ KB

Two common methods to indicate where values in a DataFrame are missing are `isna` and `isnull`. They are exactly the same methods, but with different names.

In [10]:
# Notice we have a Pandas Series of True and False values
df['interest_paid'].isna().head()

0    False
1    False
2    False
3    False
4    False
Name: interest_paid, dtype: bool

In [11]:
interest_missing = df['interest_paid'].isna()

In [12]:
# Looks at the row that contains the NaN for interest_paid
df.loc[interest_missing,:]

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
35,36,15940.06,NaN,593.99,15346.07,0.0702,Toyota Sienna

In [13]:
# Keep in mind that we can use the not operator (~) to negate the filter
# every row that doesn't have a nan is returned.
df.loc[~interest_missing,:]

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,1,34689.96,202.93,484.30,34205.66,0.0702,Toyota Sienna
1,2,34205.66,200.10,487.13,33718.53,0.0702,Toyota Sienna
2,3,33718.53,197.25,489.98,33228.55,0.0702,Toyota Sienna
3,4,33228.55,194.38,492.85,32735.70,0.0702,Toyota Sienna
4,5,32735.70,191.50,495.73,32239.97,0.0702,Toyota Sienna
5,6,32239.97,188.60,498.63,31741.34,0.0702,Toyota Sienna
6,7,31741.34,185.68,501.55,31239.79,0.0702,Toyota Sienna
7,8,31239.79,182.75,504.48,30735.31,0.0702,Toyota Sienna
8,9,30735.31,179.80,507.43,30227.88,0.0702,Toyota Sienna
9,10,30227.88,176.83,510.40,29717.48,0.0702,Toyota Sienna
10,11,29717.48,173.84,513.39,29204.09,0.0702,Toyota Sienna
11,12,29204.09,170.84,516.39,28687.70,0.0702,Toyota Sienna
12,13,28687.70,167.82,519.41,28168.29,0.0702,Toyota Sienna
13,14,28168.29,164.78,522.45,27645.84,0.0702,Toyota Sienna
14,15,27645.84,161.72,525.51,27120.33,0.0702,Toyota Sienna
15,16,27120.33,158.65,528.58,26591.75,0.0702,Toyota Sienna
16,17,26591.75,155.56,531.67,26060.08,0.0702,Toyota Sienna
17,18,26060.08,152.45,534.78,25525.30,0.0702,Toyota Sienna
18,19,25525.30,149.32,537.91,24987.39,0.0702,Toyota Sienna
19,20,24987.39,146.17,541.06,24446.33,0.0702,Toyota Sienna
20,21,24446.33,143.01,544.22,23902.11,0.0702,Toyota Sienna
21,22,23902.11,139.82,547.41,23354.70,0.0702,Toyota Sienna
22,23,23354.70,136.62,550.61,22804.09,0.0702,Toyota Sienna
23,24,22804.09,133.40,553.83,22250.26,0.0702,Toyota Sienna
24,25,22250.26,130.16,557.07,21693.19,0.0702,Toyota Sienna
25,26,21693.19,126.90,560.33,21132.86,0.0702,Toyota Sienna
26,27,21132.86,123.62,563.61,20569.25,0.0702,Toyota Sienna
27,28,20569.25,120.33,566.90,20002.35,0.0702,Toyota Sienna
28,29,20002.35,117.01,570.22,19432.13,0.0702,Toyota Sienna
29,30,19432.13,113.67,573.56,18858.57,0.0702,Toyota Sienna
30,31,18858.57,110.32,576.91,18281.66,0.0702,Toyota Sienna
31,32,18281.66,106.94,580.29,17701.37,0.0702,Toyota Sienna
32,33,17701.37,103.55,583.68,17117.69,0.0702,Toyota Sienna
33,34,17117.69,100.13,587.10,16530.59,0.0702,Toyota Sienna
34,35,16530.59,96.70,590.53,15940.06,0.0702,Toyota Sienna
36,37,15346.07,89.77,597.46,14748.61,0.0702,Toyota Sienna
37,38,14748.61,86.27,600.96,14147.65,0.0702,Toyota Sienna
38,39,14147.65,82.76,604.47,13543.18,0.0702,Toyota Sienna
39,40,13543.18,79.22,608.01,12935.17,0.0702,Toyota Sienna
40,41,12935.17,75.67,611.56,12323.61,0.0702,Toyota Sienna
41,42,12323.61,72.09,615.14,11708.47,0.0702,Toyota Sienna
42,43,11708.47,68.49,618.74,11089.73,0.0702,Toyota Sienna
43,44,11089.73,64.87,622.36,10467.37,0.0702,Toyota Sienna
44,45,10467.37,61.23,626.00,9841.37,0.0702,Toyota Sienna
45,46,9841.37,57.57,629.66,9211.71,0.0702,Toyota Sienna
46,47,9211.71,53.88,633.35,8578.36,0.0702,Toyota Sienna
47,48,8578.36,50.18,637.05,7941.31,0.0702,Toyota Sienna
48,49,7941.31,46.45,640.78,7300.53,0.0702,Toyota Sienna
49,50,7300.53,42.70,644.53,6656.00,0.0702,Toyota Sienna
50,51,6656.00,38.93,648.30,6007.70,0.0702,Toyota Sienna
51,52,6007.70,35.14,652.09,5355.61,0.0702,Toyota Sienna
52,53,5355.61,31.33,655.90,4699.71,0.0702,Toyota Sienna
53,54,4699.71,27.49,659.74,4039.97,0.0702,Toyota Sienna
54,55,4039.97,23.63,663.60,3376.37,0.0702,Toyota Sienna
55,56,3376.37,19.75,667.48,2708.89,0.0702,Toyota Sienna
56,57,2708.89,15.84,671.39,2037.50,0.0702,Toyota Sienna
57,58,2037.50,11.91,675.32,1362.18,0.0702,Toyota Sienna
58,59,1362.18,7.96,679.27,682.91,0.0702,Toyota Sienna
59,60,682.91,3.99,683.24,-0.33,0.0702,Toyota Sienna

In [14]:
# The code counts the number of missing values
# sum() works because Booleans are a subtype of integers. 
df['interest_paid'].isna().sum()

1

In [ ]:
True + False + False