In [1]:
# Import libraries
import pandas as pd
import numpy as np

### Load Excel File

In [2]:
filename = 'data/car_financing.xlsx'
df = pd.read_excel(filename)

## Renaming and Deleting Columns
It is often the case where you change your column names or remove unnecessary columns.

### Rename columns

Here are two popular ways to rename dataframe columns.
1. <b>dictionary substitution</b>: very useful if you only want to rename a few of the columns.
2. <b>list replacement</b>: requires a full list of names (in my experience, this is more error prone).

In [3]:
# DataFrame before renaming columns
df.head()

,Month,Starting Balance,Repayment,Interest Paid,Principal Paid,New Balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [8]:
# This wont work as there is a space in the column name
# I want to fix that
df['interest_rate']

0      0.0702
1      0.0702
2      0.0702
3      0.0702
4      0.0702
        ...
403    0.0290
404    0.0290
405    0.0290
406    0.0290
407    0.0290
Name: interest_rate, Length: 408, dtype: float64

In [9]:
# Approach 1 dictionary substitution using rename method
df = df.rename(columns={'Starting Balance': 'starting_balance',
                        'Interest Paid': 'interest_paid', 
                        'Principal Paid': 'principal_paid',
                        'New Balance': 'new_balance'})

In [10]:
# DataFrame after renaming columns
df.head()

,Month,starting_balance,Repayment,interest_paid,principal_paid,new_balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [11]:
# Approach 2 list replacement
# Only changing Month -> month, but we need to list the rest of the columns
df.columns = ['month',
              'starting_balance',
              'Repayment',
              'interest_paid',
              'principal_paid',
              'new_balance',
              'term',
              'interest_rate',
              'car_type']

In [12]:
df.head()

,month,starting_balance,Repayment,interest_paid,principal_paid,new_balance,term,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,60,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,60,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,60,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,60,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,60,0.0702,Toyota Sienna

In [14]:
df['term'].value_counts()

term
60    240
48     96
36     72
Name: count, dtype: int64

### Deleting Columns

In [15]:
# Approach 1
# This approach allows you to drop multiple columns at a time 
df = df.drop(columns=['term'])

In [16]:
df.head()

,month,starting_balance,Repayment,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,1,34689.96,687.23,202.93,484.30,34205.66,0.0702,Toyota Sienna
1,2,34205.66,687.23,200.10,487.13,33718.53,0.0702,Toyota Sienna
2,3,33718.53,687.23,197.25,489.98,33228.55,0.0702,Toyota Sienna
3,4,33228.55,687.23,194.38,492.85,32735.70,0.0702,Toyota Sienna
4,5,32735.70,687.23,191.50,495.73,32239.97,0.0702,Toyota Sienna

In [17]:
# Approach 2 use the del command
del df['Repayment']

In [18]:
df.head()

,month,starting_balance,interest_paid,principal_paid,new_balance,interest_rate,car_type
0,1,34689.96,202.93,484.30,34205.66,0.0702,Toyota Sienna
1,2,34205.66,200.10,487.13,33718.53,0.0702,Toyota Sienna
2,3,33718.53,197.25,489.98,33228.55,0.0702,Toyota Sienna
3,4,33228.55,194.38,492.85,32735.70,0.0702,Toyota Sienna
4,5,32735.70,191.50,495.73,32239.97,0.0702,Toyota Sienna